driverName = com.mysql.jdbc.Driver
url = jdbc:mysql://localhost:3306/springmvcbasicfree
user = root
password = 

#driverName = com.mysql.jdbc.Driver
#url = jdbc:mysql://sql212.epizy.com/epiz_34035083_twinkle?autoReconnect=true&useSSL=true
#user = epiz_34035083
#password = chanquang202